### ISSUE TITLE
Dependencies Fail to Build with Fluent Asserts 0.12.3 & DMD v2.083.1

### ISSUE THREAD

**Issue by vnayar** [gedaiu/fluent-asserts#87]
For reference, this is on an Ubuntu 18.04 LTS system.

Building a project using Fluent Asserts 0.12.3 and DMD v2.083.1 results in a build failure that seems to originate from one of Fluent Assert's dependencies, Vibe 0.8.4.

The errors are shown below:
```
$ dub test --force
...
/home/vnayar/projects/s2geometry-d/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:487: undefined reference to `SSLv23_server_method'
../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/.dub/build/openssl-unittest-linux.posix-x86_64-dmd_2083-D7CD14B8E87984FDB1E0559879CA5174/libvibe-d_tls.a(openssl_f9_569.o): In function `_D4vibe6stream7openssl14OpenSSLContext11setDHParamsMFNeAyaZv':
/home/vnayar/projects/s2geometry-d/../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/vibe/stream/openssl.d:725: undefined reference to `get_rfc3526_prime_2048'
../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/.dub/build/openssl-unittest-linux.posix-x86_64-dmd_2083-D7CD14B8E87984FDB1E0559879CA5174/libvibe-d_tls.a(safestack_600_449.o): In function `_D6deimos7openssl9safestack__T10SKM_sk_numTSQBqQBm6x509v315GENERAL_NAME_stZ__TQBwZQCaFNbPSQDkQDgQDb__T8STACK_OFTQCrZQoZi':
/home/vnayar/projects/s2geometry-d/../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/safestack.d:140: undefined reference to `sk_num'
../../.dub/packages/vibe-d-0.8.4/vibe-d/tls/.dub/build/openssl-unittest-linux.posix-x86_64-dmd_2083-D7CD14B8E87984FDB1E0559879CA5174/libvibe-d_tls.a(safestack_602_516.o): In function `_D6deimos7openssl9safestack__T12SKM_sk_valueTSQBsQBo6x509v315GENERAL_NAME_stZ__TQByZQCcFNbPSQDmQDiQDd__T8STACK_OFTQCrZQoiZPQDa':
/home/vnayar/projects/s2geometry-d/../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/safestack.d:142: undefined reference to `sk_value'
collect2: error: ld returned 1 exit status
```

**Comment by vnayar** [comment]
My mistake again, Vibe.d has its own dependencies.  In this case, the error was resolved by installing libssl1.0-dev.  For example, with the command:  `sudo apt install libssl1.0-dev`
